# Jupyter Book configuration
# Minimal, you can customize later if needed
title: "Stats Project: Pandas vs. Pure Python"
author: "Your Name"
only_build_toc_files: true
execute:
  execute_notebooks: auto
  timeout: 120
sphinx:
  config:
    html_theme_options:
      navigation_depth: 3
    language: zh_CN