
# https://jupyterbook.org/customize/config.html

title: "Computing Project I"
author: "Yiran Ge"

# https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true
  execute_notebooks: "auto"
  timeout: 120

sphinx:
  config:
    # https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
    myst_heading_anchors: 4
    # https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
      - https://cdn.plot.ly/plotly-latest.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
    